language: python
python: 
  - 3.3
install: 
  - pip install -r requirements.txt --use-mirrors
  - git clone https://github.com/Gab-km/konira_portable
  - python ./konira_portable/setup.py install
script:
  - cd lib/test
  - konira
notifications:
  on_success: always
