language: python
python: 
  - 3.3
install: 
  - pip install -r requirements.txt --use-mirrors
  - git clone https://github.com/alfredodeza/konira.git
  - python ./konira/setup.py install
script:
  - cd lib/test
  - konira
notifications:
  on_success: always
